version: '3'

services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: myparcelcom/auth-module-php:v1-dev
    working_dir: /opt/auth-module
    volumes:
      - .:/opt/auth-module
      - composercache:/tmp

volumes:
  composercache:
    driver: local
