services:
  php:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: myparcelcom/auth-module-php:v2-dev
    working_dir: /opt/auth-module
    volumes:
      - .:/opt/auth-module
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - composercache:/tmp

volumes:
  composercache:
    driver: local
